### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by malakada** [melissanoelle/dominion-viewer#1]
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)
```

During laptop lid close.

**Comment by andrewrk** [comment]
in here:

``` js
wss.on('connection', function(ws) {

}
```

you want:

``` js
ws.on('error', function(err) {
   console.error("client connection error: ", err.message);
});
```

later you'll probably want to replace the log message with either kicking them from the game, gracefully notifying the other player that their opponent disconnected, or prepare for them to reconnect to recover the game, etc.
